# Generated by Django 3.0.8 on 2020-08-01 00:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True, verbose_name='Murió')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(help_text='Ingrese el nombre del género (p.ej Ciencia Ficción, Terror, etc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.TextField(help_text='Ingrese una breve descripción del libro', max_length=1000)),
                ('ISBN', models.CharField(help_text="13 Caracteres <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>", max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor')),
                ('genero', models.ManyToManyField(help_text='Seleccione un género para este libro', to='catalog.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaLibro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para este libro en particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('impreso', models.CharField(max_length=200)),
                ('devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('M', 'Mantenimiento'), ('P', 'En préstamo'), ('D', 'Disponible'), ('R', 'Reservado')], default='M', help_text='Disponibilidad del libro', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Libro')),
            ],
            options={
                'ordering': ['devolucion'],
            },
        ),
    ]
