# Generated by Django 3.0.8 on 2020-08-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='libro',
            name='lenguaje',
            field=models.CharField(blank=True, choices=[('E', 'Espanol'), ('I', 'Ingles')], default='E', help_text='Lenguaje en que esta escrito el libro', max_length=1),
        ),
    ]
