# Generated by Django 3.0.8 on 2020-08-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200803_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_muerte',
        ),
    ]
