# Generated by Django 3.0.8 on 2020-09-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200923_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
