# Generated by Django 3.0.8 on 2020-09-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200923_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancialibro',
            options={'ordering': ['devolucion'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
    ]
